
server:
  port: 8090

spring:
  jpa:
    database: SQL_SERVER
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: SQL
    url: jdbc:sqlserver://localhost;databaseName=Asesores
    username: user2
    password: 123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
